plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation 'org.junit.jupiter:junit-jupiter:6.1.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.2'
    testImplementation("com.approvaltests:approvaltests:31.0.0")
    testImplementation("com.google.code.gson:gson:2.14.0")
}

test{
    useJUnitPlatform()
}
